resource_group_name  = "rg-tfstate-stage"
storage_account_name = "ststagetfstate001"
container_name        = "aks-stage"
key                    = "aks/stage/terraform.tfstate"
use_azuread_auth      = true