AWSTemplateFormatVersion: '2010-09-09'
Description: "S3 Dev Bucket"
Resources:
    DevS3Bucket:
      Type: "AWS::S3::Bucket"
      Properties:
          VersioningConfiguration: 
            Status: Enabled