resource_group_name  = "rg-tfstate-prod"
storage_account_name = "stprodtfstate001"
container_name        = "aks-prod"
key                    = "aks/prod/terraform.tfstate"
use_azuread_auth      = true